# Generated by Django 5.2.1 on 2025-08-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='process.floor'),
            preserve_default=False,
        ),
    ]
