# Generated by Django 5.2.1 on 2025-08-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_remove_apartment_location_remove_floor_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='process.floor'),
        ),
    ]
