# Generated by Django 5.2.1 on 2025-08-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_apartment_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='YearlyRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_rents', to='process.apartment')),
            ],
            options={
                'unique_together': {('apartment', 'year')},
            },
        ),
    ]
