# Generated by Django 5.2.1 on 2026-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_remove_apartment_price_alter_floor_number_yearlyrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
