# Generated by Django 5.2.1 on 2026-02-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_remove_apartment_price_alter_floor_number_yearlyrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='process.floor'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.apartment'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='process.floor'),
        ),
    ]
