# Generated by Django 5.2.1 on 2026-07-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_apartment_name_floor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renters', to='process.apartment'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
